name: ia_esp32  # Nombre de tu proyecto
description: Proyecto Flutter para el asistente con ESP32

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"  # Asegúrate de que esto esté alineado con la versión de Flutter que usas

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: ^0.8.0  # Dependencia para Bluetooth
  speech_to_text: ^5.0.1  # Dependencia para reconocimiento de voz

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
